# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7a9ae809139d382218d8b290306bdf6a"
name = "courier"
application_url = "https://tables-abu-sees-zero.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "codesbreak.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products"

[auth]
redirect_urls = [
  "https://tables-abu-sees-zero.trycloudflare.com/auth/callback",
  "https://tables-abu-sees-zero.trycloudflare.com/auth/shopify/callback",
  "https://tables-abu-sees-zero.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
